name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Login to Docker Hub
     - uses: docker/login-action@v1
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Build the Docker image
       run:  |
             docker build -t my-dockerhub-username/my-image-name:${{ github.sha }} .
     - name: Tag Docker image
       run: |
            docker tag my-dockerhub-username/my-image-name:${{ github.sha }} my-dockerhub-username/my-image-name:1.0
     - name: Push Docker image to Docker Hub
       run: |
          docker push my-dockerhub-username/my-image-name:${{ github.sha }}
          docker push my-dockerhub-username/my-image-name:1.0
